### PR TITLE
Cache Test & Bug Fix

### PR DESCRIPTION
**Pull request by LeopardMerkava**
Cache lacks testing. However, the private nature of Cache makes that difficult.

Lets:
* Add tests for cache
* Add package-private reset function for test purposes
* Add cache to its own package (so no other class can call reset)

### CODE REVIEW

**Review by kflim — COMMENTED** [review]
Looks ok to me

**Comment by limzk126** [comment]
LGTM

**Review by limzk126 — COMMENTED** [review]
LGTM

**Review by wz27 — COMMENTED** [review]
LGTM

**Comment by eugenecsa** [comment]
lgtm

**Pull request merged**
